a_min_max: false
a_sym: false
act_bit: 4
act_tensor: false
base:
- models/ldm/lsun_churches256/config.yaml
batch_size: 8
cali_batch_size: 32
cali_ckpt: /workspace/quant_models/church_w4a8_ckpt.pth
cali_data_path: /workspace/cali_data/church.pt
cali_iters: 20000
cali_iters_a: 5000
cali_lr: 0.0004
cali_min_max: true
cali_n: 32
cali_p: 2.4
cali_st: 20
cond: false
custom_steps: 400
dpm: false
eta: 0.0
generate: null
logdir: /workspace/MoDiff/docs/paper_repro_2026-08-12/qdiff_w4a4
modulate: true
n_samples: 8
no_ema: false
out_penalty: 0.0
ptq: true
quant_act: true
quant_mode: qdiff
resume: false
resume_base: models/ldm/lsun_churches256/model.ckpt
resume_w: true
rs_sm_only: false
running_stat: false
seed: 42
skip_weight_recon: false
sm_abit: 8
vanilla_sample: false
verbose: false
w_sym: false
weight_bit: 4
