"""Emit FINDINGS.md from the committed measurements. Tables are generated; prose is not."""
import json, os
H = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sv = json.load(open(f"{H}/data/stats_variants.json"))
il = json.load(open(f"{H}/data/apply_ilp.json"))
nm = json.load(open(f"{H}/data/inmodel_nsys.json"))
PEAK, N, STEP = 696.0, 128, 77.0005
B, A = nm["int8 BEFORE"], nm["int8 AFTER"]
I4B, I4A = nm["int4 mid"], nm["int4 AFTER"]
def get(d, sub):
    return sum(v for k, v in d["per_kernel_ms_per_step"].items() if sub in k)
L = []
w = L.append
w("# Two bit-identical vectorisations: GroupNorm stats and the resize path's a_hat, -1.29 ms/step")
w("")
w("**Date** 2026-08-26 · **GPU** NVIDIA A40 · **Batch** 128 · **Arm** W8A8 + MoDiff, static delta")
w("")
w("Both changes are pure memory-access fixes inside the conv block. Neither moves a value or the")
w("order values are added in, and both are gated on **bit-identity** rather than a tolerance,")
w("because mean/inv_std feed the delta quantizer whose a_hat cache accumulates across 200 steps —")
w("one ULP and the two arms are different functions, not one function measured twice.")
w("")
w("| | before | after | delta |")
w("|---|--:|--:|--:|")
s0, s1 = get(B, "gn_stats_partials"), get(A, "gn_stats_partials")
r0, r1 = get(B, "delta_quantize_resize"), get(A, "delta_quantize_resize")
ap0, ap1 = get(B, "gn_apply_delta"), get(A, "gn_apply_delta")
rd0, rd1 = get(B, "gn_stats_reduce"), get(A, "gn_stats_reduce")
w(f"| GN stats (`gn_stats_partials_chanmajor` → `_vec2`) | {s0:.3f} | {s1:.3f} | **{s1-s0:+.3f}** |")
w(f"| GN+resize+delta (`..._resize_nhwc_kernel`, a_hat vec2) | {r0:.3f} | {r1:.3f} | **{r1-r0:+.3f}** |")
w(f"| GN apply (unchanged — see §3) | {ap0:.3f} | {ap1:.3f} | {ap1-ap0:+.3f} |")
w(f"| stats reduce (unchanged) | {rd0:.3f} | {rd1:.3f} | {rd1-rd0:+.3f} |")
tot0, tot1 = s0+r0+ap0+rd0, s1+r1+ap1+rd1
w(f"| **GN family total** | **{tot0:.3f}** | **{tot1:.3f}** | **{tot1-tot0:+.3f}** ({100*(tot1-tot0)/tot0:+.1f}%) |")
w(f"| GPU busy, whole step | {B['gpu_busy_ms_per_step']:.3f} | {A['gpu_busy_ms_per_step']:.3f} | "
  f"{A['gpu_busy_ms_per_step']-B['gpu_busy_ms_per_step']:+.3f} |")
w("")
w(f"Attributed conservatively: the two targeted kernels account for **{(s1-s0)+(r1-r0):+.3f} ms/step**")
w(f"= **{100*abs((s1-s0)+(r1-r0))/STEP:.2f}% of the 77.00 ms steady step**. The larger GPU-busy delta")
w("includes a few hundredths spread across untouched kernels, which is run-to-run drift, not effect.")
w("")
w("---")
w("")
w("## 1. GroupNorm statistics: 49.8% → 71.6% of peak bandwidth")
w("")
w("`gn_stats_partials_chanmajor_kernel` was **latency-bound, not bandwidth-bound** — nsys put it at")
w("49.8% of peak against the apply kernel's 84.5% on the same tensors. Two causes:")
w("")
w("1. one 2-byte load per thread per `hw` iteration, so a warp requests 64 B — half a sector;")
w("2. the `hw` loop is not unrolled and the accumulate is serial, so exactly one load per thread is")
w("   in flight.")
w("")
w("Fix: a thread owns **two adjacent channels** loaded as one `__half2`, and the `hw` loop processes")
w("four positions with the loads hoisted ahead of the first dependent add.")
w("")
w("**Why it is bit-identical.** Each channel keeps its own fp32 accumulator; that accumulator still")
w("walks `hw` ascending (unrolling reorders no adds, it only issues loads earlier); shared memory is")
w("still indexed by channel and the group combine still sums CPG channels in ascending index. Only")
w("the address and the load instruction change.")
w("")
w("Microbenchmark over all 18 real GN shapes, batch 128, freq-weighted:")
w("")
w("| variant | ms/step |")
w("|---|--:|")
for k in ["v0 shipped", "v1 hw-unroll", "v2 vec2-chan", "v3 both"]:
    w(f"| {k} | {sum(r['med'][k]*r['freq'] for r in sv):.3f} |")
w("")
w("Per shape (all bit-identical to v0):")
w("")
w("| shape | freq | v0 | v3 | speedup | % peak v0 → v3 |")
w("|---|--:|--:|--:|--:|--:|")
for r in sv:
    C = int(r["shape"].split(",")[0]); HW = int(r["shape"].split(",")[1].split("x")[0])**2
    ne = N * C * HW
    g0 = ne*2/(r["med"]["v0 shipped"]*1e-3)/1e9; g3 = ne*2/(r["med"]["v3 both"]*1e-3)/1e9
    w(f"| `{r['shape']}` | {r['freq']} | {r['med']['v0 shipped']:.4f} | {r['med']['v3 both']:.4f} | "
      f"{r['med']['v0 shipped']/r['med']['v3 both']:.2f}× | {100*g0/PEAK:.0f}% → {100*g3/PEAK:.0f}% |")
w("")
w("It also removes the need for the `K > 1` channel split on this UNet: the block is `C/2` threads,")
w("so every `C <= 2048` fits under the 1024-thread cap where the scalar kernel needed `K = 2` from")
w("C = 1152 up.")
w("")
w("Gate: [`test_gn_stats_vec2.py`](../../integration/tests/test_gn_stats_vec2.py) — 16 shapes,")
w("driven through the public `group_norm_silu_delta_quantize_nhwc` entry point with")
w("`MODIFF_GN_STATS_VEC2` on and off in **forked processes** (the flag is a function-local static,")
w("so an in-process A/B silently measures one variant twice). It asserts three things, not one:")
w("codes and a_hat bit-identical, codes not all zero, **and the profiler saw two different stats")
w("kernels** — without that last check the test would pass just as happily if the flag were never")
w("read, which is the failure mode OPEN_ITEMS A22 records.")
w("")
w("## 2. The resize path's a_hat: two scalar accesses → one vec2")
w("")
w("`group_norm_silu_delta_quantize_resize_nhwc_kernel` is the second-largest GN kernel and it also")
w("carries a_hat. `compute_pair` already vectorised x, gamma, beta and the modulation, but the a_hat")
w("read-modify-write did not: two scalar `__half` loads at `ci` and `ci + 1`, two scalar")
w("`__float2half_rn` stores. Both the UP and DOWN paths, now one `gn_load2` / `gn_store2` each.")
w("")
w("Bit-identity is structural — the same two 16-bit values, and `__float22half2_rn` rounds each")
w("component to nearest even exactly as the two `__float2half_rn` calls did. The one real")
w("precondition is that `ci` be even, which holds because `c_start = g·CPG` with CPG even; that is")
w("now a `TORCH_CHECK` in the launcher rather than a comment, since a misaligned `reinterpret_cast`")
w("is undefined behaviour that can appear to work.")
w("")
w(f"In-model: **{r0:.3f} → {r1:.3f} ms/step**.")
w("")
w("Gate: [`test_gn_resize_ahat_vec2.py`](../../integration/tests/test_gn_resize_ahat_vec2.py), a")
w("two-build capture/compare over 4 shapes × {upsample, downsample} × {int8, packed int4} ×")
w("{mod, no mod} = 32 cases. All 32 bit-identical, 198,870,120 nonzero codes for non-vacuity.")
w("")
w("### The control that mattered")
w("")
w("The first attempt at this gate compared **end-to-end images** between the two builds. They")
w("differed — and that is meaningless: two runs of the *same* build also differ. Measured here,")
w("HEAD against itself over 64 images gave `sha256 4f15fc19…` and `44dbe9b2…`. That is")
w("[OPEN_ITEMS A18/A19](../OPEN_ITEMS.md) (cross-process floor 8.7/255) showing up as a")
w("would-be false alarm. Without the self-comparison it would have read as *the change broke")
w("correctness*. Kernel-level capture under a fixed seed is the instrument that resolves.")
w("")
w("## 3. The apply kernel is already at the roof — measured, not assumed")
w("")
w("`gn_apply_delta_quantize_flat_vec2_kernel`, where a_hat's read-modify-write lives, is 84.5% of")
w("peak. Its grid covers every element in one pass, so there is no loop to unroll; the equivalent")
w("lever is to shrink the grid and give each thread U independent pairs. Elements are independent,")
w("so any assignment is bit-identical by construction (asserted for every U).")
w("")
w("| U | ms/step, freq-weighted over 18 shapes |")
w("|---|--:|")
for u in ["1", "2", "4", "8"]:
    w(f"| {u}{' (as shipped)' if u == '1' else ''} | {sum(r['med'][u]*r['freq'] for r in il):.3f} |")
w("")
w("**Negative: U = 1 as shipped is best.** Only the tiny shapes gain (`768,2x2` 1.07×, `1536,2x2`")
w("1.06×) and together they are worth about 0.009 ms/step — not worth a dispatch. The kernel is")
w("genuinely bandwidth-bound, which is consistent with")
w("[ahat_overlap_2026-08-26](../ahat_overlap_2026-08-26/FINDINGS.md): a_hat's 4 B/elem are")
w("irreducible without changing what is stored.")
w("")
w("## 4. Two honest nulls from finishing the job")
w("")
w("**The decoder skip-concat fold was still on the scalar kernel** — 14.2 of 58.9 stats calls per")
w("step in the W4A4 arm (the W8A8 arm does not take that path). It was extended to vec2 too, with")
w("the boundary argument that a pair never straddles C1 because every C1 here is a multiple of 32,")
w("and it is now covered by phase 2 of the gate. **The gain is 0.049 ms/step: neutral.** Recorded")
w("because the conversion is real, correct and measured — not because it bought anything.")
w("")
w(f"**Unexplained, and orthogonal to this change: the same stats kernel costs 36% more in the W4A4")
w(f"arm than in W8A8** — {sum(v for k,v in I4A['per_kernel_ms_per_step'].items() if 'gn_stats_partials' in k):.3f} vs "
  f"{sum(v for k,v in A['per_kernel_ms_per_step'].items() if 'gn_stats_partials' in k):.3f} ms/step, on identical shapes with")
w("identical call counts (19.0 at C=384, 22.8 at C=768, 8.5 at C=192, …, verified per block size in")
w("the trace). The GN input is fp16 in both arms, so the kernel does the same work on the same bytes.")
w("It predates this change — the pre-cat2 W4A4 trace shows the same gap — so it is not a regression,")
w("but it is 0.96 ms/step sitting in the W4A4 arm with no explanation, and worth its own look.")
w("")
w("## Scope and limitations")
w("")
w("- **The cat2 / skip-concat variant of the stats kernel is untouched.** It also writes a")
w("  concatenation, and folding a vectorised store into it is a separate change with its own gate.")
w("- **Odd channels-per-group** falls back to the scalar stats kernel and is rejected outright by")
w("  the resize launcher. Every C in this UNet is a multiple of 32 with G = 32, so CPG is even.")
w("- **C1 + C2 > 2048 declines vec2** (block would exceed 1024 threads) and correctly falls back to")
w("  the scalar K-split kernel; the 1536+768 fold is the one such shape and the gate asserts the")
w("  fallback rather than treating it as a pass by accident.")
w("- **In-model numbers come from one nsys trace per arm**, windowed to the second sample batch")
w("  (20 DDIM steps). Kernel durations are CUPTI activity records and are not inflated by the")
w("  profiler; wall time is, which is why GPU-busy rather than wall is quoted throughout.")
w("- **`ncu` is unavailable** (`ERR_NVGPUCTRPERM`), so `% of peak` is derived from measured")
w("  durations and analytic byte counts, as everywhere else in this project.")
w("")
open(f"{H}/FINDINGS.md", "w").write("\n".join(L) + "\n")
print("wrote FINDINGS.md")
