"""Is the shipped W4A4 delta table sized for the delta the deployed model actually produces?

WHY SUSPECT IT. W4A4 MoDiff measures 1.0469 relL2, WORSE than its own PTQ baseline at 0.8642, and
the samples are high-frequency structured scribble rather than the PTQ arm's fog. MoDiff making
things worse is the paper's central claim inverted, and the shape of the failure -- structure that
accumulates rather than detail that is lost -- is what a clipping delta quantizer inside a feedback
loop looks like.

THE HYPOTHESIS. qdiff calibrated the delta on `cali_churches_residual.pt`, generated by
`--generate residual`, which runs BEFORE `if opt.ptq:` and therefore samples the **fp16** model
(qdiff_bridge FINDINGS §5b:157). On that trajectory `a_hat_{t+1}` is essentially unquantized, so the
temporal delta `a_t - a_hat_{t+1}` is the true inter-step motion of the activation. The deployed
kernel's `a_hat_{t+1}` is a **4-bit reconstruction** carrying a large quantization error, so its
delta is that motion PLUS that error. At W8A8 the error is small and the two agree; at W4A4 the
activation grid is 3.77/15, so the error can dominate the motion.

If that is what is happening, the shipped table is sized for the wrong quantity, the delta clips on
every modulated step, and MoDiff's feedback term carries the clipped error forward -- which is
exactly a mechanism for getting worse than not modulating at all.

THE MEASUREMENT. `begin_delta_calibration_int4` arms the tree's own observation path, which forces
the layer into DYNAMIC mode for the pass and records the EXACT delta absmax the kernel computes,
per step index, per layer. That is ground truth for the deployed configuration. Compare it against
the shipped table's implied absmax, `Q_DELTA / scale`.

int8 runs as a control. If the ratio is ~1 there and >>1 at int4, the cause is the 4-bit feedback
and not the export.

Run: python docs/state_report_2026-08-12/scripts/debug_w4a4_delta_scale.py   # ~4 min, needs the GPU
"""
import json
import os
import statistics
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
os.chdir(ROOT)
sys.path[:0] = [ROOT, os.path.join(ROOT, "src/taming-transformers"),
                os.path.join(ROOT, "integration/benchmarks/report"),
                os.path.join(ROOT, "docs/modiff_correctness_2026-08-03/scripts")]

import torch                                                                # noqa: E402
import dynamic_delta_ab as H                                               # noqa: E402
import integration.benchmarks.benchmark_ldm as B                           # noqa: E402

OUT = "docs/state_report_2026-08-12/data/debug_w4a4_delta_scale.json"
SEED = 1234


def probe(mode, steps=50, batch=4):
    from integration.kernels.int4_optimized import (OptimizedInt4Conv2d,
                                                    begin_delta_calibration_int4)
    from integration.kernels.int8_optimized import (OptimizedInt8Conv2d,
                                                    begin_delta_calibration_int8)
    is4 = mode == "int4"
    Q = 7.0 if is4 else 127.0
    cls = OptimizedInt4Conv2d if is4 else OptimizedInt8Conv2d
    arm = begin_delta_calibration_int4 if is4 else begin_delta_calibration_int8
    table_path = B._default_delta_path(mode)
    table = torch.load(table_path, map_location="cpu", weights_only=True)

    H.STEPS, H.BATCH, H.SEED = steps, batch, SEED
    H.AUTO_DELTA_TABLE = True
    r, m, s = H.build(mode, B._default_calibration_path(mode), "static")

    # Warm-up in the SHIPPED configuration first: the quantized attention self-calibrates over its
    # first forwards, and observing during that would record a model that is still settling.
    H.latent(r, m, s)

    n = arm(m.model.diffusion_model, reset=True)
    print(f"  armed observation on {n} layers", flush=True)
    H.SEED = SEED
    H.latent(r, m, s)               # this pass runs DYNAMIC and records the exact delta absmax

    rows = []
    for mod in m.model.diffusion_model.modules():
        if not isinstance(mod, cls) or mod.layer_name not in table:
            continue
        # THE TWO PATHS OBSERVE DIFFERENT QUANTITIES, and reading int4's attribute on an int8 layer
        # silently yields nothing. int4 records the EXACT absmax the dynamic kernel computed; int8
        # records CODE maxima at the known non-clipping observation scale act_scale/OBS_DIV, so its
        # absmax has to be divided back out (end_delta_calibration:1674 does the same).
        if is4:
            obs = getattr(mod, "_delta_absmax_obs", None)
            if obs is None:
                continue
            o = obs.detach().to("cpu", torch.float64)
        else:
            cm = getattr(mod, "_delta_code_max", None)
            if cm is None:
                continue
            obs_scale = float(mod.static_input_scale.item()) / 4.0     # OBS_DIV
            o = cm.detach().to("cpu", torch.float64) / obs_scale
        seen = o[o > 0]
        if not seen.numel():
            continue
        assumed = Q / float(table[mod.layer_name].median())
        rows.append({"layer": mod.layer_name,
                     "observed_absmax_median": float(seen.median()),
                     "observed_absmax_max": float(seen.max()),
                     "assumed_absmax": assumed,
                     "ratio_observed_over_assumed": float(seen.median()) / assumed})
    del r, m, s
    torch.cuda.empty_cache()
    return rows, table_path


def main():
    os.environ["MODIFF_LINEAR"] = "0"
    out = {}
    for mode in ("int8", "int4"):
        print(f"=== {mode}", flush=True)
        rows, tp = probe(mode)
        if not rows:
            print(f"  FAIL: no layers observed for {mode}")
            return 1
        rat = [r["ratio_observed_over_assumed"] for r in rows]
        obs = [r["observed_absmax_median"] for r in rows]
        asm = [r["assumed_absmax"] for r in rows]
        clipping = sum(1 for x in rat if x > 1.0)
        out[mode] = {"table": tp, "layers": rows,
                     "observed_median": statistics.median(obs),
                     "assumed_median": statistics.median(asm),
                     "ratio_median": statistics.median(rat),
                     "ratio_max": max(rat), "layers_clipping": clipping, "n": len(rows)}
        print(f"  observed delta absmax  median {statistics.median(obs):8.4f}")
        print(f"  table assumes          median {statistics.median(asm):8.4f}   ({os.path.basename(tp)})")
        print(f"  observed / assumed     median {statistics.median(rat):8.2f}x   worst "
              f"{max(rat):.2f}x   over-range on {clipping}/{len(rows)} layers", flush=True)

    r8, r4 = out["int8"]["ratio_median"], out["int4"]["ratio_median"]
    print()
    if r4 > 2.0 and r4 > r8 * 1.8:
        print(f"CONFIRMED: the W4A4 table is sized for a delta {r4:.1f}x smaller than the deployed "
              f"model produces, while int8's is off by only {r8:.1f}x. The delta clips on every "
              f"modulated step and MoDiff's feedback carries the clipped error forward -- which is "
              f"how a MoDiff arm ends up WORSE than its own PTQ baseline.")
    elif r4 > 2.0 and r8 > 2.0:
        print(f"BOTH tables under-size the delta (int8 {r8:.1f}x, int4 {r4:.1f}x). The calibration "
              f"trajectory, not the bit width, is the problem -- qdiff's a_hat is unquantized.")
    else:
        print(f"NOT CONFIRMED: int4 ratio {r4:.2f}x, int8 {r8:.2f}x. The table is not obviously "
              f"mis-sized; the W4A4 failure is somewhere else.")

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    json.dump({"seed": SEED, "modes": out}, open(OUT, "w"), indent=1)
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
